name: Build and Deploy to Ubuntu Server

on:
  push:
    branches: [main]    # Ganti jika branch deploy kamu bukan main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Build TypeScript (Babel)
        run: npm run build

      - name: Upload dist/ via SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          source: "dist"
          target: "${{ secrets.SERVER_PATH }}"

      - name: Restart PM2 on server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            nvm use 21 || nvm install 21
            node -v
            npm -v
            npm install -g pm2
            pm2 --version || { echo "PM2 installation failed"; exit 1; }
            pm2 list | grep novaapp_api || pm2 start dist/server.js --name novaapp_api
            pm2 restart novaapp_api
            pm2 save
