name: Build and Deploy to Ubuntu Server

on:
  push:
    branches: [main]    # Ganti jika branch deploy kamu bukan main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Build TypeScript (Babel)
        run: npm run build

      - name: Deploy dist/ via rsync over SSH
        uses: burnett01/rsync-deployments@7.0.2
        with:
          switches: -avz --delete
          path: dist/
          remote_path: ${{ secrets.SERVER_PATH }}/dist
          remote_host: ${{ secrets.SERVER_HOST }}
          remote_user: ${{ secrets.SERVER_USER }}
          remote_key: ${{ secrets.SERVER_SSH_KEY }}

      - name: Restart PM2 on server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd ${{ secrets.SERVER_PATH }}
            pm2 start dist/index.js --name novaapp_api || pm2 restart novaapp_api